datasource.url=jdbc:oracle:thin:@localhost:1521/PWLDB
datasource.username=pwl_app
datasource.password=AppPass456!
datasource.driver=oracle.jdbc.OracleDriver
jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
jpa.hibernate.ddl-auto=update
jpa.show-sql=true
jpa.format-sql=true